nfl_franchises = ['atl', 'buf', 'car', 'chi', 'cin', 'cle', 'clt', 'crd', 'dal', 'den', 'det', 'gnb', 'htx', 'jax', 'kan', 'mia', 'min', 'nor', 'nwe', 'nyg', 'nyj', 'oti', 'phi', 'pit', 'rai', 'ram', 'rav', 'sdg', 'sea', 'sfo', 'tam', 'was']

pro_football_headers =   ['SeasonWeek', 'Day', 'Date', 'Time', 'Boxscore', 'Result', 'Overtime', 'Rec', 'HomeOrAway', 'Opponent', 'PointsFor', 'PointsAgainst', 
            'Off1stDowns', 'OffTotYards', 'OffPassYards', 'OffRushYards', 'OffTurnoverLost', 
            'Opp1stDowns', 'OppTotYards', 'OppPassYards', 'OppRushYards', 'OppTurnoverLost', 
            'ExpectedPointsOffense', 'ExpectedPointsDefense', 'ExpectedPointsSpTms']

nfl_names = {'Arizona Cardinals':'crd',
    'Atlanta Falcons':'atl',
    'Baltimore Ravens':'rav',
    'Buffalo Bills':'buf',
    'Carolina Panthers':'car',
    'Chicago Bears':'chi',
    'Cincinnati Bengals':'cin',
    'Cleveland Browns':'cle',
    'Dallas Cowboys':'dal',
    'Denver Broncos':'den',
    'Detroit Lions':'det',
    'Green Bay Packers':'gnb',
    'Houston Texans':'htx',
    'Indianapolis Colts':'clt',
    'Jacksonville Jaguars':'jax',
    'Kansas City Chiefs':'kan',
    'Las Vegas Raiders':'rai',
    'Los Angeles Chargers':'sdg',
    'Los Angeles Rams':'ram',
    'Miami Dolphins':'mia',
    'Minnesota Vikings':'min',
    'New England Patriots':'nwe',
    'New Orleans Saints':'nor',
    'New York Giants':'nyg',
    'New York Jets':'nyj',
    'Philadelphia Eagles':'phi',
    'Pittsburgh Steelers':'pit',
    'San Francisco 49ers':'sfo',
    'Seattle Seahawks':'sea',
    'Tampa Bay Buccaneers':'tam',
    'Tennessee Titans':'oti',
    'Washington Football Team':'was'}

