nfl_football_headers = [
    "SeasonWeek",
    "Day",
    "Date",
    "Time",
    "Boxscore",
    "Result",
    "Overtime",
    "Rec",
    "HomeOrAway",
    "Opponent",
    "PointsFor",
    "PointsAgainst",
    "Off1stDowns",
    "OffTotYards",
    "OffPassYards",
    "OffRushYards",
    "OffTurnoverLost",
    "Opp1stDowns",
    "OppTotYards",
    "OppPassYards",
    "OppRushYards",
    "OppTurnoverLost",
    "ExpectedPointsOffense",
    "ExpectedPointsDefense",
    "ExpectedPointsSpTms",
]

nfl_teams = {
    "Arizona Cardinals": "crd",
    "Atlanta Falcons": "atl",
    "Baltimore Ravens": "rav",
    "Buffalo Bills": "buf",
    "Carolina Panthers": "car",
    "Chicago Bears": "chi",
    "Cincinnati Bengals": "cin",
    "Cleveland Browns": "cle",
    "Dallas Cowboys": "dal",
    "Denver Broncos": "den",
    "Detroit Lions": "det",
    "Green Bay Packers": "gnb",
    "Houston Texans": "htx",
    "Indianapolis Colts": "clt",
    "Jacksonville Jaguars": "jax",
    "Kansas City Chiefs": "kan",
    "Las Vegas Raiders": "rai",
    "Los Angeles Chargers": "sdg",
    "Los Angeles Rams": "ram",
    "Miami Dolphins": "mia",
    "Minnesota Vikings": "min",
    "New England Patriots": "nwe",
    "New Orleans Saints": "nor",
    "New York Giants": "nyg",
    "New York Jets": "nyj",
    "Philadelphia Eagles": "phi",
    "Pittsburgh Steelers": "pit",
    "San Francisco 49ers": "sfo",
    "Seattle Seahawks": "sea",
    "Tampa Bay Buccaneers": "tam",
    "Tennessee Titans": "oti",
    "Washington Football Team": "was",
}

ncaa_football_headers = [
    "SeasonWeek",
    "Date",
    "Time",
    "Day",
    "School",
    "HomeOrAway",
    "Opponent",
    "Conference",
    "Result",
    "PointsFor",
    "PointsAgainst",
    "W",
    "L",
    "Streak",
    "Notes",
]

ncaa_teams = {
    "air-force": "air-force",
    "akron": "akron",
    "alabama": "alabama",
    "appalachian-state": "appalachian-state",
    "arizona": "arizona",
    "arizona-state": "arizona-state",
    "arkansas": "arkansas",
    "arkansas-state": "arkansas-state",
    "army": "army",
    "auburn": "auburn",
    "ball-state": "ball-state",
    "baylor": "baylor",
    "boise-state": "boise-state",
    "boston-college": "boston-college",
    "bowling-green-state": "bowling-green-state",
    "buffalo": "buffalo",
    "brigham-young": "brigham-young",
    "california": "california",
    "central-michigan": "central-michigan",
    "charlotte": "charlotte",
    "cincinnati": "cincinnati",
    "clemson": "clemson",
    "coastal-carolina": "coastal-carolina",
    "colorado": "colorado",
    "colorado-state": "colorado-state",
    "connecticut": "connecticut",
    "duke": "duke",
    "east-carolina": "east-carolina",
    "eastern-michigan": "eastern-michigan",
    "florida": "florida",
    "florida-atlantic": "florida-atlantic",
    "florida-international": "florida-international",
    "florida-state": "florida-state",
    "fresno-state": "fresno-state",
    "georgia": "georgia",
    "georgia-southern": "georgia-southern",
    "georgia-state": "georgia-state",
    "georgia-tech": "georgia-tech",
    "hawaii": "hawaii",
    "houston": "houston",
    "illinois": "illinois",
    "indiana": "indiana",
    "iowa": "iowa",
    "iowa-state": "iowa-state",
    "james-madison": "james-madison",
    "kansas": "kansas",
    "kansas-state": "kansas-state",
    "kent-state": "kent-state",
    "kentucky": "kentucky",
    "liberty": "liberty",
    "louisiana-lafayette": "louisiana-lafayette",
    "louisiana-tech": "louisiana-tech",
    "louisiana-monroe": "louisiana-monroe",
    "louisville": "louisville",
    "louisiana-state": "louisiana-state",
    "marshall": "marshall",
    "maryland": "maryland",
    "massachusetts": "massachusetts",
    "memphis": "memphis",
    "miami-fl": "miami-fl",
    "miami-oh": "miami-oh",
    "michigan": "michigan",
    "michigan-state": "michigan-state",
    "middle-tennessee-state": "middle-tennessee-state",
    "minnesota": "minnesota",
    "mississippi-state": "mississippi-state",
    "missouri": "missouri",
    "navy": "navy",
    "nebraska": "nebraska",
    "nevada": "nevada",
    "nevada-las-vegas": "nevada-las-vegas",
    "new-mexico": "new-mexico",
    "new-mexico-state": "new-mexico-state",
    "north-carolina": "north-carolina",
    "north-carolina-state": "north-carolina-state",
    "north-texas": "north-texas",
    "northern-illinois": "northern-illinois",
    "northwestern": "northwestern",
    "notre-dame": "notre-dame",
    "ohio": "ohio",
    "ohio-state": "ohio-state",
    "oklahoma": "oklahoma",
    "oklahoma-state": "oklahoma-state",
    "old-dominion": "old-dominion",
    "mississippi": "mississippi",
    "oregon": "oregon",
    "oregon-state": "oregon-state",
    "penn-state": "penn-state",
    "pittsburgh": "pittsburgh",
    "purdue": "purdue",
    "rice": "rice",
    "rutgers": "rutgers",
    "san-diego-state": "san-diego-state",
    "san-jose-state": "san-jose-state",
    "southern-methodist": "southern-methodist",
    "south-alabama": "south-alabama",
    "south-carolina": "south-carolina",
    "south-florida": "south-florida",
    "southern-mississippi": "southern-mississippi",
    "stanford": "stanford",
    "syracuse": "syracuse",
    "temple": "temple",
    "tennessee": "tennessee",
    "texas": "texas",
    "texas-am": "texas-am",
    "texas-christian": "texas-christian",
    "texas-state": "texas-state",
    "texas-tech": "texas-tech",
    "toledo": "toledo",
    "troy": "troy",
    "tulane": "tulane",
    "tulsa": "tulsa",
    "alabama-birmingham": "alabama-birmingham",
    "central-florida": "central-florida",
    "ucla": "ucla",
    "southern-california": "southern-california",
    "utah": "utah",
    "utah-state": "utah-state",
    "texas-el-paso": "texas-el-paso",
    "texas-san-antonio": "texas-san-antonio",
    "vanderbilt": "vanderbilt",
    "virginia": "virginia",
    "virginia-tech": "virginia-tech",
    "wake-forest": "wake-forest",
    "washington": "washington",
    "washington-state": "washington-state",
    "west-virginia": "west-virginia",
    "western-kentucky": "western-kentucky",
    "western-michigan": "western-michigan",
    "wisconsin": "wisconsin",
    "wyoming": "wyoming",
}
