nfl_football_headers = [
    "SeasonWeek",
    "Day",
    "Date",
    "Time",
    "Boxscore",
    "Result",
    "Overtime",
    "Rec",
    "HomeOrAway",
    "Opponent",
    "PointsFor",
    "PointsAgainst",
    "Off1stDowns",
    "OffTotYards",
    "OffPassYards",
    "OffRushYards",
    "OffTurnoverLost",
    "Opp1stDowns",
    "OppTotYards",
    "OppPassYards",
    "OppRushYards",
    "OppTurnoverLost",
    "ExpectedPointsOffense",
    "ExpectedPointsDefense",
    "ExpectedPointsSpTms",
]

nfl_teams = {
    "Arizona Cardinals": "crd",
    "Atlanta Falcons": "atl",
    "Baltimore Ravens": "rav",
    "Buffalo Bills": "buf",
    "Carolina Panthers": "car",
    "Chicago Bears": "chi",
    "Cincinnati Bengals": "cin",
    "Cleveland Browns": "cle",
    "Dallas Cowboys": "dal",
    "Denver Broncos": "den",
    "Detroit Lions": "det",
    "Green Bay Packers": "gnb",
    "Houston Texans": "htx",
    "Indianapolis Colts": "clt",
    "Jacksonville Jaguars": "jax",
    "Kansas City Chiefs": "kan",
    "Las Vegas Raiders": "rai",
    "Los Angeles Chargers": "sdg",
    "Los Angeles Rams": "ram",
    "Miami Dolphins": "mia",
    "Minnesota Vikings": "min",
    "New England Patriots": "nwe",
    "New Orleans Saints": "nor",
    "New York Giants": "nyg",
    "New York Jets": "nyj",
    "Philadelphia Eagles": "phi",
    "Pittsburgh Steelers": "pit",
    "San Francisco 49ers": "sfo",
    "Seattle Seahawks": "sea",
    "Tampa Bay Buccaneers": "tam",
    "Tennessee Titans": "oti",
    "Washington Football Team": "was",
}

ncaa_football_headers = [
    "SeasonWeek",
    "Date",
    "Time",
    "Day",
    "School",
    "HomeOrAway",
    "Opponent",
    "Conference",
    "Result",
    "PointsFor",
    "PointsAgainst",
    "W",
    "L",
    "Streak",
    "Notes",
]

ncaa_teams = {
    "Air Force": "air-force",
    "Akron": "akron",
    "Alabama": "alabama",
    "UAB": "alabama-birmingham",
    "Appalachian State": "appalachian-state",
    "Arizona": "arizona",
    "Arizona State": "arizona-state",
    "Arkansas": "arkansas",
    "Arkansas State": "arkansas-state",
    "Army": "army",
    "Auburn": "auburn",
    "Ball State": "ball-state",
    "Baylor": "baylor",
    "Boise State": "boise-state",
    "Boston College": "boston-college",
    "Bowling Green": "bowling-green-state",
    "BYU": "brigham-young",
    "Buffalo": "buffalo",
    "California": "california",
    "UCF": "central-florida",
    "Central Michigan": "central-michigan",
    "Charlotte": "charlotte",
    "Cincinnati": "cincinnati",
    "Clemson": "clemson",
    "Coastal Carolina": "coastal-carolina",
    "Colorado": "colorado",
    "Colorado State": "colorado-state",
    "Connecticut": "connecticut",
    "Duke": "duke",
    "East Carolina": "east-carolina",
    "Eastern Michigan": "eastern-michigan",
    "Florida": "florida",
    "Florida Atlantic": "florida-atlantic",
    "Florida International": "florida-international",
    "Florida State": "florida-state",
    "Fresno State": "fresno-state",
    "Georgia": "georgia",
    "Georgia Southern": "georgia-southern",
    "Georgia State": "georgia-state",
    "Georgia Tech": "georgia-tech",
    "Hawaii": "hawaii",
    "Houston": "houston",
    "Illinois": "illinois",
    "Indiana": "indiana",
    "Iowa": "iowa",
    "Iowa State": "iowa-state",
    "Kansas": "kansas",
    "Kansas State": "kansas-state",
    "Kent State": "kent-state",
    "Kentucky": "kentucky",
    "Liberty": "liberty",
    "Louisiana": "louisiana-lafayette",
    "Louisiana-Monroe": "louisiana-monroe",
    "LSU": "louisiana-state",
    "Louisiana Tech": "louisiana-tech",
    "Louisville": "louisville",
    "Marshall": "marshall",
    "Maryland": "maryland",
    "Massachusetts": "massachusetts",
    "Memphis": "memphis",
    "Miami (FL)": "miami-fl",
    "Miami (OH)": "miami-oh",
    "Michigan": "michigan",
    "Michigan State": "michigan-state",
    "Middle Tennessee State": "middle-tennessee-state",
    "Minnesota": "minnesota",
    "Ole Miss": "mississippi",
    "Mississippi State": "mississippi-state",
    "Missouri": "missouri",
    "Navy": "navy",
    "Nebraska": "nebraska",
    "Nevada": "nevada",
    "Nevada-Las Vegas": "nevada-las-vegas",
    "New Mexico": "new-mexico",
    "New Mexico State": "new-mexico-state",
    "North Carolina": "north-carolina",
    "North Carolina State": "north-carolina-state",
    "Northern Illinois": "northern-illinois",
    "North Texas": "north-texas",
    "Northwestern": "northwestern",
    "Notre Dame": "notre-dame",
    "Ohio": "ohio",
    "Ohio State": "ohio-state",
    "Oklahoma": "oklahoma",
    "Oklahoma State": "oklahoma-state",
    "Old Dominion": "old-dominion",
    "Oregon": "oregon",
    "Oregon State": "oregon-state",
    "Penn State": "penn-state",
    "Pitt": "pittsburgh",
    "Purdue": "purdue",
    "Rice": "rice",
    "Rutgers": "rutgers",
    "San Diego State": "san-diego-state",
    "San Jose State": "san-jose-state",
    "South Alabama": "south-alabama",
    "South Carolina": "south-carolina",
    "USC": "southern-california",
    "SMU": "southern-methodist",
    "Southern Mississippi": "southern-mississippi",
    "South Florida": "south-florida",
    "Stanford": "stanford",
    "Syracuse": "syracuse",
    "Temple": "temple",
    "Tennessee": "tennessee",
    "Texas": "texas",
    "Texas A&M": "texas-am",
    "Texas Christian": "texas-christian",
    "UTEP": "texas-el-paso",
    "UTSA": "texas-san-antonio",
    "Texas State": "texas-state",
    "Texas Tech": "texas-tech",
    "Toledo": "toledo",
    "Troy": "troy",
    "Tulane": "tulane",
    "Tulsa": "tulsa",
    "UCLA": "ucla",
    "Utah": "utah",
    "Utah State": "utah-state",
    "Vanderbilt": "vanderbilt",
    "Virginia": "virginia",
    "Virginia Tech": "virginia-tech",
    "Wake Forest": "wake-forest",
    "Washington": "washington",
    "Washington State": "washington-state",
    "Western Kentucky": "western-kentucky",
    "Western Michigan": "western-michigan",
    "West Virginia": "west-virginia",
    "Wisconsin": "wisconsin",
    "Wyoming": "wyoming",
}


ncaa_ranks = [
    "(1)",
    "(2)",
    "(3)",
    "(4)",
    "(5)",
    "(6)",
    "(7)",
    "(8)",
    "(9)",
    "(10)",
    "(11)",
    "(12)",
    "(13)",
    "(14)",
    "(15)",
    "(16)",
    "(17)",
    "(18)",
    "(19)",
    "(20)",
    "(21)",
    "(22)",
    "(23)",
    "(24)",
    "(25)",
]
